// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search visible GoMall marketplace products by name/category, optionally filtered by price range. Returns up to 25 matches.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text search over product name/category."),
    category: z.string().trim().optional().describe("Filter by category (exact match)."),
    max_price: z.number().positive().optional().describe("Maximum price in KES."),
    min_price: z.number().nonnegative().optional().describe("Minimum price in KES."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, max_price, min_price, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("marketplace_products").select("id,name,category,price,original_price,image_url,description").eq("hidden", false).limit(limit ?? 25);
    if (query) q = q.or(`name.ilike.%${query}%,category.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    if (typeof max_price === "number") q = q.lte("price", max_price);
    if (typeof min_price === "number") q = q.gte("price", min_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single GoMall marketplace product by id.",
  inputSchema: {
    id: z2.string().trim().min(1).describe("Product id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("marketplace_products").select("id,name,category,price,original_price,image_url,description,details,hidden").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List distinct visible product categories in the GoMall marketplace.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("marketplace_products").select("category").eq("hidden", false);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const categories = Array.from(
      new Set((data ?? []).map((r) => r.category).filter(Boolean))
    ).sort();
    return {
      content: [{ type: "text", text: JSON.stringify(categories) }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/tools/track-order.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var track_order_default = defineTool4({
  name: "track_order",
  title: "Track order",
  description: "Track a GoMall order status by order id. Requires the M-Pesa phone number used at checkout for verification.",
  inputSchema: {
    order_id: z3.string().trim().min(1).describe("Order id from checkout confirmation."),
    phone: z3.string().trim().min(9).describe("M-Pesa phone number used at checkout.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id, phone }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const normalized = phone.replace(/\s+/g, "").replace(/^\+/, "").replace(/^0/, "254");
    const { data, error } = await supabase.from("orders").select("id,status,total_amount,delivery_fee,county,town,mpesa_receipt,created_at,items").eq("id", order_id).eq("phone_number", normalized).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: "No matching order for that id + phone." }],
        isError: true
      };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gomall-mcp",
  title: "GoMall MCP",
  version: "0.1.0",
  instructions: "Tools for the GoMall marketplace. Use `search_products` and `list_categories` to browse phones, beauty, and personal care items. Use `get_product` for details and `track_order` to check an order status (requires the M-Pesa phone used at checkout).",
  tools: [search_products_default, get_product_default, list_categories_default, track_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
